### ISSUE TITLE
[Bug] RoleColorEverywhere broken in voice users list

### ISSUE THREAD

**Issue by iwa** [Vendicated/Vencord#2359]
### Discord Account

iwa.sh

### What happens when the bug or crash occurs?

RoleColorEverywhere's voice users list settings is no longer working (maybe due to a recent discord update?)

![image](https://github.com/Vendicated/Vencord/assets/19956672/3631f8c3-3abe-4269-8a8b-2bca06dfbf6e)
![image](https://github.com/Vendicated/Vencord/assets/19956672/f3240c55-c605-46b7-86a7-a79a1877514b)

### What is the expected behaviour?

Should show all usernames in the voice channel list with role colors

### How do you recreate this bug or crash?

1. Update Discord & vencord
2. Enable the plugin & the setting
3. Restart
4. Go in a voice channel

### Errors

none found

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by lewisakura** [comment]
Believe this should be fixed by #2356. Reopen if this is not the case.

**Comment by VaelophisNyx** [comment]
This appears to be broken again, unfortunately

**Comment by Nuckyz** [comment]
> This appears to be broken again, unfortunately

Fixed on [761e6b3](https://github.com/Vendicated/Vencord/commit/761e6b39ed0e1d0c7aa6f6b8dc7a49ccbd12ba11)

**Comment by MatTheoo89** [comment]
Good evening, even when updating the version 761e6b3, the plugin continues to not show the colors for the vocal channels only

**Comment by Nuckyz** [comment]
I'm sorry, my color blindness made me think the color of the name of a person in the voice chat was pink, when in reality it was gray. So in-fact, it was not fixed

**Comment by Nuckyz** [comment]
Actually fixed here, but not yet going to release the update

https://github.com/Vendicated/Vencord/commit/7af733c7c81e2b5d40fe0ec12c2525336e113716

**Comment by VaelophisNyx** [comment]
Broken once again, kinda blows that users can't open issues and are funneled into a server to do any reporting. Github is THE way to manage this shit, discord sucks for issue reports.
Anyway it's not even registering as loaded in the console like other plugins now.
